apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - lhc.net/argo-project-protection
spec:
  description: "Infrastructure tools"
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/lhc/infra.git'
  destinations:
  - namespace: infra
    server: https://kubernetes.default.svc
